name: WearApp
version: 0.0.1
dependencies:
  angular: '>=0.12.0'
  animation:
    git: git://github.com/platelk/Animation.git
  browser: '>= 0.10.0'
  cameleon:
    git: git://github.com/platelk/cameleon.dart.git